services:
  database:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: avaliacao
    ports:
      - 5432:5432
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    restart: always 

